# Generated by Django 5.0.1 on 2024-02-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('expirationDate', models.DateField()),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('sex', models.CharField(max_length=50)),
                ('workingForm', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
