# Generated by Django 4.2.10 on 2024-03-02 12:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('testdate', models.DateTimeField(null=True)),
                ('coverLetter', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecruitmentPost',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('expirationDate', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('sex', models.CharField(max_length=50)),
                ('workingForm', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('wage', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
