# Generated by Django 4.2.10 on 2024-02-15 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentpost',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employer'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='users.applicant'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='recruitment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='jobs.recruitmentpost'),
        ),
    ]
