# Generated by Django 5.0.1 on 2024-02-01 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='areas',
            field=models.ManyToManyField(to='users.area'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='carrers',
            field=models.ManyToManyField(to='users.career'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employer'),
        ),
    ]
