# Generated by Django 5.0.1 on 2024-02-01 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='users.applicant')),
                ('jobPost', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='jobs.jobpost')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
