# Generated by Django 5.0.1 on 2024-02-02 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_recruitment_alter_jobapplication_jobpost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitment',
            name='carrers',
        ),
    ]
