# Generated by Django 5.0.1 on 2024-02-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_recruitment_carrers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruitment',
            options={'ordering': ['-created_date', 'updated_date']},
        ),
        migrations.RemoveField(
            model_name='recruitment',
            name='areas',
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
