# Generated by Django 5.0.1 on 2024-02-13 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_recruitment_options_remove_recruitment_areas_and_more'),
        ('users', '0011_rename_area_applicant_areas_remove_applicant_sex_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='jobPost',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='description',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cv',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='RecruitmentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('expirationDate', models.DateField()),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('sex', models.CharField(max_length=50)),
                ('workingForm', models.CharField(max_length=255)),
                ('carrer', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('wage', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employer')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='recruitment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='jobs.recruitmentpost'),
        ),
        migrations.DeleteModel(
            name='Recruitment',
        ),
    ]
