# Generated by Django 5.0.1 on 2024-02-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_is_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_applicant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='companyName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='companySize',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='mediaLink',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='workingForm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/%Y/%m'),
        ),
    ]
