# Generated by Django 5.0.1 on 2024-02-02 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_applicant_alter_employer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='sport',
            field=models.CharField(choices=[('Martial Arts', [('judo', 'Judo'), ('karate', 'Karate')]), ('Racket', [('badminton', 'Badminton'), ('tennis', 'Tennis')]), ('unknown', 'Unknown')], default='unknown', max_length=255),
        ),
    ]
