# Generated by Django 5.0.1 on 2024-02-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_applicant_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='sport',
        ),
        migrations.AlterField(
            model_name='career',
            name='name',
            field=models.CharField(choices=[('KD_BH', 'Kinh doanh / Bán hàng')], default='KD_BH', max_length=255),
        ),
    ]
