# Generated by Django 5.0.1 on 2024-02-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_applicant_sport_alter_career_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='name',
            field=models.CharField(choices=[('KD_BH', 'Kinh doanh / Bán hàng'), ('B_PD', 'Biên / Phiên dịch'), ('BC_TH', 'Báo chí / Truyền hình'), ('BC_VT', 'Bưu chính - Viễn thông'), ('BH', 'Bảo hiểm'), ('BDS', 'Bất động sản'), ('CK_V_NT', 'Chứng khoán / Vàng / Ngoại tệ'), ('CNC', 'Công nghệ cao'), ('CK_CT_TDH', 'Cơ khí / Chế tạo / Tự động hóa'), ('DL', 'Du lịch'), ('CHOOSE_CAREER', 'Ngành nghề')], default='CHOOSE_CAREER', max_length=255),
        ),
    ]
