# Generated by Django 5.0.1 on 2024-02-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_applicant_career_delete_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='experience',
            field=models.CharField(choices=[('Tất cả kinh nghiệm', 'Tất cả kinh nghiệm'), ('Chưa có kinh nghiệm', 'Chưa có kinh nghiệm'), ('Dưới 1 năm', 'Dưới 1 năm'), ('1 năm', '1 năm'), ('2 năm', '2 năm'), ('3 năm', '3 năm'), ('4 năm', '4 năm'), ('5 năm', '5 năm'), ('Trên 5 năm', 'Trên 5 năm')], default='Tất cả kinh nghiệm', max_length=50),
        ),
        migrations.AddField(
            model_name='applicant',
            name='wage',
            field=models.CharField(choices=[('Tất cả mức lương', 'Tất cả mức lương'), ('Dưới 10 triệu', 'Dưới 10 triệu'), ('10 - 15 triệu', '10 - 15 triệu'), ('15 - 20 triệu', '15 - 20 triệu'), ('20 - 25 triệu', '20 - 25 triệu'), ('25 - 30 triệu', '25 - 30 triệu'), ('30 - 50 triệu', '30 - 50 triệu'), ('Trên 50 triệu', 'Trên 50 triệu'), ('Thỏa thuận', 'Thỏa thuận')], default='Tất cả mức lương', max_length=50),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='career',
            field=models.CharField(choices=[('Tất cả ngành nghề', 'Tất cả ngành nghề'), ('Kinh doanh / Bán hàng', 'Kinh doanh / Bán hàng'), ('Biên / Phiên dịch', 'Biên / Phiên dịch'), ('Báo chí / Truyền hình', 'Báo chí / Truyền hình'), ('Bưu chính - Viễn thông', 'Bưu chính - Viễn thông'), ('Bảo hiểm', 'Bảo hiểm'), ('Bất động sản', 'Bất động sản'), ('Chứng khoán / Vàng / Ngoại tệ', 'Chứng khoán / Vàng / Ngoại tệ'), ('Công nghệ thông tin', 'Công nghệ thông tin'), ('Cơ khí / Chế tạo / Tự động hóa', 'Cơ khí / Chế tạo / Tự động hóa'), ('Du lịch', 'Du lịch')], default='Tất cả ngành nghề', max_length=50),
        ),
    ]
