# Generated by Django 5.0.1 on 2024-02-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='area',
            new_name='areas',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='workingForm',
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='career',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='experience',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='wage',
            field=models.CharField(max_length=255),
        ),
    ]
